version: '3.7'

volumes:
  java-app-maven-repo: {}

services:

  java-app:
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ../:/app

  java-app-test:
    image: java-app-test
    build:
      target: base
      context: ../
      dockerfile: ./docker/app/Dockerfile
    working_dir: /app
    volumes:
      - ../:/app
      - java-app-maven-repo:/root/.m2
